FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# for prod, need to run build, and then start the build from a web server
RUN npm run build

# use nginx as web server and copy the previous "stage" to the docker
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



