version: "3.8"

services: 
  server:
    # https://hub.docker.com/_/nginx
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      # using bind mount to paste our own nginx config into this web server container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # php:
  # mysql:
  # composer:
  # artisan:
  # npm: